/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: 1.5.1
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.api;

import io.swagger.model.LinkDTO;
import io.swagger.model.LinkParam;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Halo API Documentation
 *
 * <p>Documentation for Halo API
 *
 * API tests for LinkControllerApi 
 */
public class LinkControllerApiTest {


    private LinkControllerApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("http://localhost:8090", LinkControllerApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    /**
     * Creates a link
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createByUsingPOST2Test() {
        LinkParam body = null;
        //LinkDTO response = api.createByUsingPOST2(body);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Delete link by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletePermanentlyUsingDELETE2Test() {
        Integer id = null;
        //api.deletePermanentlyUsingDELETE2(id);
        
        // TODO: test validations
        
        
    }
    /**
     * Gets link detail by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUsingGET2Test() {
        Integer id = null;
        //LinkDTO response = api.getByUsingGET2(id);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Lists links
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listLinksUsingGETTest() {
        List<String> sort = null;
        //List<LinkDTO> response = api.listLinksUsingGET(sort);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Lists all link teams
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void teamsUsingGETTest() {
        //List<String> response = api.teamsUsingGET();
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Updates a link
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateByUsingPUT3Test() {
        Integer id = null;
        LinkParam body = null;
        //LinkDTO response = api.updateByUsingPUT3(id, body);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
}
