/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: 1.5.1
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.api;

import io.swagger.model.TagDTO;
import io.swagger.model.TagParam;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Halo API Documentation
 *
 * <p>Documentation for Halo API
 *
 * API tests for TagControllerApi 
 */
public class TagControllerApiTest {


    private TagControllerApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("http://localhost:8090", TagControllerApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    /**
     * Creates a tag
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTagUsingPOSTTest() {
        TagParam body = null;
        //TagDTO response = api.createTagUsingPOST(body);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Deletes a tag
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletePermanentlyUsingDELETE9Test() {
        Integer tagId = null;
        //TagDTO response = api.deletePermanentlyUsingDELETE9(tagId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Gets tag detail by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUsingGET10Test() {
        Integer tagId = null;
        //TagDTO response = api.getByUsingGET10(tagId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Lists tags
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTagsUsingGETTest() {
        List<String> sort = null;
        Boolean more = null;
        //List<TagDTO> response = api.listTagsUsingGET(sort, more);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Updates a tag
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateByUsingPUT11Test() {
        Integer tagId = null;
        TagParam body = null;
        //TagDTO response = api.updateByUsingPUT11(tagId, body);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
}
